In [1]:
!pip install kaggle
!mkdir .kaggle
!mkdir ~/.kaggle

import json
token = {"username":"tanmayakrsahni","key":"33888ab7e78c0b759c8d076db7cd57d6"}

with open('/content/.kaggle/kaggle.json', 'w') as file:
    json.dump(token, file)

!cp /content/.kaggle/kaggle.json ~/.kaggle/kaggle.json
!chmod 600 /root/.kaggle/kaggle.json

!kaggle datasets download -d paramaggarwal/fashion-product-images-small

!ls

mkdir: cannot create directory ‘.kaggle’: File exists
mkdir: cannot create directory ‘/root/.kaggle’: File exists
fashion-product-images-small.zip: Skipping, found more recently modified local copy (use --force to force download)
fashion-product-images-small.zip  myntradataset  styles.csv
images				  sample_data


In [2]:
# importing required modules 
from zipfile import ZipFile 
  
# specifying the zip file name 
file_name = "fashion-product-images-small.zip"
  
# opening the zip file in READ mode 
with ZipFile(file_name, 'r') as zip: 
    # extracting all the files 
    print('Extracting all the files now...') 
    zip.extractall() 
    print('Done!')

Extracting all the files now...
Done!


In [3]:
!ls

fashion-product-images-small.zip  myntradataset  styles.csv
images				  sample_data


In [4]:
import pandas as pd

df = pd.read_csv('styles.csv',error_bad_lines=False)

df.head()

b'Skipping line 6044: expected 10 fields, saw 11\nSkipping line 6569: expected 10 fields, saw 11\nSkipping line 7399: expected 10 fields, saw 11\nSkipping line 7939: expected 10 fields, saw 11\nSkipping line 9026: expected 10 fields, saw 11\nSkipping line 10264: expected 10 fields, saw 11\nSkipping line 10427: expected 10 fields, saw 11\nSkipping line 10905: expected 10 fields, saw 11\nSkipping line 11373: expected 10 fields, saw 11\nSkipping line 11945: expected 10 fields, saw 11\nSkipping line 14112: expected 10 fields, saw 11\nSkipping line 14532: expected 10 fields, saw 11\nSkipping line 15076: expected 10 fields, saw 12\nSkipping line 29906: expected 10 fields, saw 11\nSkipping line 31625: expected 10 fields, saw 11\nSkipping line 33020: expected 10 fields, saw 11\nSkipping line 35748: expected 10 fields, saw 11\nSkipping line 35962: expected 10 fields, saw 11\nSkipping line 37770: expected 10 fields, saw 11\nSkipping line 38105: expected 10 fields, saw 11\nSkipping line 38275: ex

id gender  ...   usage                             productDisplayName
0  15970    Men  ...  Casual               Turtle Check Men Navy Blue Shirt
1  39386    Men  ...  Casual             Peter England Men Party Blue Jeans
2  59263  Women  ...  Casual                       Titan Women Silver Watch
3  21379    Men  ...  Casual  Manchester United Men Solid Black Track Pants
4  53759    Men  ...  Casual                          Puma Men Grey T-shirt

[5 rows x 10 columns]

In [5]:
df.columns

Index(['id', 'gender', 'masterCategory', 'subCategory', 'articleType',
       'baseColour', 'season', 'year', 'usage', 'productDisplayName'],
      dtype='object')

In [6]:
df = df.dropna()

In [7]:
df.nunique()

id                    44077
gender                    5
masterCategory            7
subCategory              45
articleType             142
baseColour               46
season                    4
year                     13
usage                     8
productDisplayName    30806
dtype: int64

In [8]:
value_counts = df['articleType'].value_counts()

indexes = value_counts.index

values = value_counts.values

for i in range(len(value_counts)):

    if values[i] <1000:
        break

types_used = indexes[:i]
print(types_used)

Index(['Tshirts', 'Shirts', 'Casual Shoes', 'Watches', 'Sports Shoes',
       'Kurtas', 'Tops', 'Handbags', 'Heels', 'Sunglasses'],
      dtype='object')


In [9]:
df['gender'].value_counts()

Men       22109
Women     18357
Unisex     2126
Boys        830
Girls       655
Name: gender, dtype: int64

In [10]:
df = df[df['gender'] != 'Boys']
df = df[df['gender'] != 'Girls']

In [11]:
value_counts = df['baseColour'].value_counts()

indexes = value_counts.index

values = value_counts.values

for i in range(len(value_counts)):

    if values[i] <1000:
        break

colours_used = indexes[:i]
print(colours_used)

Index(['Black', 'White', 'Blue', 'Brown', 'Grey', 'Red', 'Green', 'Navy Blue',
       'Pink', 'Purple', 'Silver'],
      dtype='object')


In [12]:
df = df[df['articleType'].isin(types_used)]
df = df[df['baseColour'].isin(colours_used)]

In [13]:
cat_columns = ['gender', 'masterCategory', 'subCategory', 'articleType','baseColour', 'season', 'year', 'usage']

for col in cat_columns:
    print(col)
    print(df[col].unique())
    print('-------------------------')

gender
['Men' 'Women' 'Unisex']
-------------------------
masterCategory
['Apparel' 'Accessories' 'Footwear' 'Free Items']
-------------------------
subCategory
['Topwear' 'Watches' 'Shoes' 'Bags' 'Eyewear' 'Free Gifts' 'Belts']
-------------------------
articleType
['Shirts' 'Watches' 'Tshirts' 'Casual Shoes' 'Handbags' 'Kurtas'
 'Sports Shoes' 'Heels' 'Tops' 'Sunglasses']
-------------------------
baseColour
['Navy Blue' 'Silver' 'Grey' 'Green' 'Purple' 'Black' 'Blue' 'Brown'
 'White' 'Pink' 'Red']
-------------------------
season
['Fall' 'Winter' 'Summer' 'Spring']
-------------------------
year
[2011. 2016. 2012. 2015. 2014. 2010. 2013. 2018. 2017. 2007. 2009. 2008.]
-------------------------
usage
['Casual' 'Ethnic' 'Formal' 'Sports' 'Smart Casual' 'Party' 'Travel']
-------------------------


In [14]:
df['usage'].value_counts()

Casual          15804
Sports           2887
Ethnic           1407
Formal            839
Smart Casual       41
Travel              5
Party               4
Name: usage, dtype: int64

In [15]:
df = df[df['usage'] != 'Smart Casual']
df = df[df['usage'] != 'Travel']
df = df[df['usage'] != 'Party']

In [16]:
cat_columns = ['gender', 'masterCategory', 'subCategory', 'articleType','baseColour', 'season', 'year', 'usage']

for col in cat_columns:
    print(col)
    print(df[col].unique())
    print('-------------------------')

gender
['Men' 'Women' 'Unisex']
-------------------------
masterCategory
['Apparel' 'Accessories' 'Footwear' 'Free Items']
-------------------------
subCategory
['Topwear' 'Watches' 'Shoes' 'Bags' 'Eyewear' 'Free Gifts' 'Belts']
-------------------------
articleType
['Shirts' 'Watches' 'Tshirts' 'Casual Shoes' 'Handbags' 'Kurtas'
 'Sports Shoes' 'Heels' 'Tops' 'Sunglasses']
-------------------------
baseColour
['Navy Blue' 'Silver' 'Grey' 'Green' 'Purple' 'Black' 'Blue' 'Brown'
 'White' 'Pink' 'Red']
-------------------------
season
['Fall' 'Winter' 'Summer' 'Spring']
-------------------------
year
[2011. 2016. 2012. 2015. 2014. 2010. 2013. 2018. 2017. 2007. 2009. 2008.]
-------------------------
usage
['Casual' 'Ethnic' 'Formal' 'Sports']
-------------------------


In [17]:
df = df[df['subCategory'] != 'Free Gifts']

In [18]:
len(df)

20935

In [37]:
data = []

from tensorflow.keras.preprocessing.image import img_to_array
import cv2

IX = 80
IY = 60

invalid_ids = []

for name in df.id:

    try:
        image = cv2.imread('images/'+str(name)+'.jpg')
        image = cv2.resize(image, (IX,IY) )
        image = img_to_array(image)
        data.append(image)        
    except:   
        invalid_ids.append(name)
    
    


In [38]:
print('invalid ids:')
print(invalid_ids)

invalid ids:
[39403, 39425]


In [39]:
labels = []

used_columns = ['subCategory','baseColour']

for index, row in df.iterrows():

    if row['id'] in invalid_ids:
        continue

    tags = []

    for col in used_columns:
        tags.append(row[col])

    labels.append(tags)

In [40]:
import numpy as np

data = np.array(data, dtype="float") / 255.0
labels = np.array(labels)

print(labels)

[['Topwear' 'Navy Blue']
 ['Watches' 'Silver']
 ['Topwear' 'Grey']
 ...
 ['Shoes' 'White']
 ['Topwear' 'Blue']
 ['Watches' 'Pink']]


In [41]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
labels = mlb.fit_transform(labels)

print(mlb.classes_)
print(labels[0])

['Bags' 'Belts' 'Black' 'Blue' 'Brown' 'Eyewear' 'Green' 'Grey'
 'Navy Blue' 'Pink' 'Purple' 'Red' 'Shoes' 'Silver' 'Topwear' 'Watches'
 'White']
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0]


In [42]:
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D

inputShape = (IY, IX, 3)


model = Sequential()

model.add(Conv2D(64, (3, 3), padding="same",input_shape=inputShape))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))

model.add(Flatten()) 

model.add(Dense(128))
model.add(Activation('sigmoid'))


out = len(mlb.classes_)

model.add(Dense(out))
model.add(Activation('sigmoid'))
                    
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['mse'])

In [43]:

from sklearn.model_selection import train_test_split


(trainX, testX, trainY, testY) = train_test_split(data,labels, test_size=0.1, random_state=42)

In [44]:
batch = 32
E = 50


model.fit(x=trainX,y=trainY,
          epochs=E ,verbose=1)

Epoch 1/50
589/589 [==============================] - 5s 8ms/step - loss: 0.2918 - accuracy: 0.1257
Epoch 2/50
589/589 [==============================] - 5s 8ms/step - loss: 0.1247 - accuracy: 0.2617
Epoch 3/50
589/589 [==============================] - 5s 8ms/step - loss: 0.1014 - accuracy: 0.2630
Epoch 4/50
589/589 [==============================] - 5s 8ms/step - loss: 0.0903 - accuracy: 0.2634
Epoch 5/50
589/589 [==============================] - 5s 8ms/step - loss: 0.0829 - accuracy: 0.2632
Epoch 6/50
589/589 [==============================] - 5s 8ms/step - loss: 0.0791 - accuracy: 0.2669
Epoch 7/50
589/589 [==============================] - 5s 8ms/step - loss: 0.0740 - accuracy: 0.2726
Epoch 8/50
589/589 [==============================] - 5s 8ms/step - loss: 0.0729 - accuracy: 0.2673
Epoch 9/50
589/589 [==============================] - 5s 8ms/step - loss: 0.0668 - accuracy: 0.2702
Epoch 10/50
589/589 [==============================] - 5s 8ms/step - loss: 0.0663 - accuracy: 0.2674

In [65]:
preds = model.predict(testX)

pred_binarized = []

for pred in preds:
    vals = []
    for val in pred:
        if val > 0.5:
            vals.append(1)
        else:
            vals.append(0)
    pred_binarized.append(vals) 

pred_binarized = np.array(pred_binarized)     

In [53]:
testY

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [51]:
from sklearn.metrics import mean_squared_error

In [66]:
true_test_labels = mlb.inverse_transform(testY)
pred_test_labels = mlb.inverse_transform(pred_binarized)

In [76]:
for i in range(30):

    true_label = true_test_labels[i]

    pred_label = pred_test_labels[i]

    print(true_label,pred_label)

('Black', 'Topwear') ('Black', 'Topwear')
('Red', 'Shoes') ('Red', 'Shoes')
('Green', 'Topwear') ('Green', 'Topwear')
('Grey', 'Shoes') ('Grey', 'Shoes')
('Navy Blue', 'Shoes') ('Navy Blue', 'Shoes')
('Black', 'Topwear') ('Black', 'Topwear')
('Blue', 'Topwear') ('Blue', 'Topwear')
('Brown', 'Shoes') ('Shoes',)
('Grey', 'Shoes') ('Grey', 'Shoes')
('Topwear', 'White') ('Topwear',)
('Blue', 'Topwear') ('Blue', 'Topwear')
('Blue', 'Topwear') ('Blue', 'Topwear')
('Topwear', 'White') ('Topwear', 'White')
('Topwear', 'White') ('Topwear', 'White')
('Green', 'Topwear') ('Green', 'Topwear')
('Topwear', 'White') ('Topwear', 'White')
('Blue', 'Topwear') ('Topwear',)
('Green', 'Topwear') ('Green', 'Topwear')
('Black', 'Shoes') ('Black', 'Shoes')
('Black', 'Shoes') ('Black', 'Shoes')
('Silver', 'Watches') ('Blue', 'Watches')
('Red', 'Shoes') ('Red', 'Shoes')
('Shoes', 'Silver') ('Shoes',)
('Brown', 'Shoes') ('Brown', 'Shoes')
('Navy Blue', 'Topwear') ('Topwear',)
('Topwear', 'White') ('Topwear',)
('